---
config:
  theme: redux-color
---
mindmap
ABC
  História
    Python
    Influências
  tipos
    NUMBER
      exact «default» 
        racionais com precisão arbitrária
      inexact
    TEXT
      base 1
      mutável
      fatiável com @ e |
    COMPOUND
      "tupla"
      empacotar/desempacotar
      não iterável, não indexável
    LIST
      base 1
      mutável
      sempre ordenada
      homogênea
    TABLE
      chaves ordenadas
      chaves e valores homogêneos
      iteração acessa valores
  Comandos
  Funções
  Ambiente